export const APPENDABLE_LINE_FIELDS = new Set(["harmfulHabits", "clinicalPicture"]);
export const EXTRA_LINE_COUNT = 2;
export const INLINE_GAP_MIN = 2;
export const INLINE_GAP_MAX = 6;

export const INITIAL_PATIENT_COUNT = 3;

export const RANDOM_PATIENT_NAMES = [
    "Anna",
    "Altyn",
    "Toya",
    "Khulan",
    "Lun",
    "Burduk",
    "Tolkowy",
    "Oktai",
    "Laska",
    "Mariya",
    "Mishka",
    "Nara",
    "Nika",
    "Bobok",
    "Pavel",
    "Shchur",
    "Lyuta",
    "Fila",
    "Vera",
    "Yargi",
    "Olusha",
    "Zhytochnik",
    "Yunat",
    "Emilia",
    "Sotnik",
    "Tuutei",
    "Voronok",
    "Astrild",
    "Chernyak",
    "Myrosya",
    "Petrel",
    "Khariton",
    "Aristarkh",
    "Sakh Men",
    "Poshinok",
    "Kira",
    "Marfa",
    "Lyudmila",
    "Yegor",
    "Makar",
    "Dmitry",
    "Semyon",
    "Konstantin",
    "Sergey",
    "Ilya",
];

export const RANDOM_PATIENT_LAST_NAMES = [
    "Ankudinov",
    "Baskakov",
    "Gantimurova",
    "Goncharova",
    "Grishin",
    "Kabanov",
    "Karmin",
    "Kharitonov",
    "Kudrin",
    "Mishchenko",
    "Naraeva",
    "Sablin",
    "Sotnik",
    "Yunatov",
];

//TODO: single 50% of the time, married 20%, widowed 10%, betrothed 10%, divorced 5%
export const RANDOM_MARITAL_STATUSES = ["single", "married", "widowed", "betrothed", "divorced"];

export const RANDOM_OCCUPATIONS = [
    "abbatoir clerk",
    "apothecary assistant",
    "bakery hand",
    "bookkeeper",
    "carter",
    "chimney sweep",
    "dock porter",
    "dressmaker",
    "factory stoker",
    "ferryman",
    "gravedigger's assistant",
    "laundress",
    "night watchman",
    "rail yard mechanic",
    "schoolteacher",
    "seamstress",
    "soap boiler",
    "station clerk",
    "tallow renderer",
    "tannery worker",
    "town orderly",
    "warehouse tallyman",
    "aspiring herb bride",
    "works for Stamatin",
    "dancer",
    "drunk",
    "shopkeeper",
    "dyer",
    "street sweeper",
    "cutpurse thug",
    "Termitary guard",
    "vagrant",
    "apprentice herbalist",
    "apprentice midwife",
    "manual laborer",
    "bandit",
    "wannabe scientist",
    "wannabe artist",
    "'artist'",
    "studies botany",
    "studies anatomy",
    "studies medicine",
    "shop-floor worker",
    "charlatan healer",
    "dealer",
    "housewife",
    "does not remember",
    "unclear (?)",
    "academy student",
    "herb bride",
    "accountant",
    "solider",
    "teacher",
    "keeps bees",
];

export const RANDOM_RESIDENCES = [
    "Tanners",
    "Skinners",
    "Hindquarters",
    "Factory",
    "The Crude Sprawl",
    "Flank",
    "Chine",
    "Backbone",
    "Marrow",
    "Gut",
    "Maw",
    "Spleen",
    "Warehouses",
    "Atrium",
    "Bridge Square",
    "Shekhen steppe village",
    "does not remember",
    "no premament residence",
    "unclear (?)",
    "sleeps on the streets",
];

export const PHOTO_PATHS = Array.from({ length: 24 }, (_, index) => {
    return `assets/patient_${String(index + 1).padStart(2, "0")}.png`;
});

//TODO: list of harmul habits and clinical picture elements to randomly add to patients

//TODO: add toottips to symptoms
export const symptomGroups = [
    {
        id: "central-nervous-system",
        title: "Central Nervous System",
        icon: "assets/icon_brain.png",
        tooltip:
            "The central nervous system includes the brain and spinal cord. Problems with them can range from mental disorders and behavioral changes to common headaches.",
        symptoms: [
            "Headache",
            "Bulimia",
            "Hallucinations",
            "Hydrophobia",
            "Loss of coordination",
            "Memory lapses",
        ],
    },
    {
        id: "vision",
        title: "Vision",
        icon: "assets/icon_eye.png",
        tooltip:
            "Eye afflictions can vary in nature and manifest both externally—in the organ's blood supply and physiology—and directly through the patient's sensations.",
        symptoms: [
            "Darkened eye capillaries",
            "Red eyes",
            "Irregular pupil shape",
            "Photophobia",
            "Visual impairment",
        ],
    },
    {
        id: "mucous-membranes",
        title: "Mucous Membranes",
        icon: "assets/icon_mouth.png",
        tooltip:
            "Mucous membranes line internal cavities such as auditory canals and airways, partially extending to their external openings, and also reduce friction—for instance, between bones.",
        symptoms: [
            "Sore throat",
            "Joint pain",
            "Lip lesions",
            "Redness around the nose",
            "Hearing impairment",
        ],
    },
    {
        id: "respiratory-system",
        title: "Respiratory System",
        icon: "assets/icon_lungs.png",
        tooltip:
            "Lung damage, besides obvious breathing difficulties, can manifest as visible signs on the patient's body—for example, due to oxygen depletion in the blood.",
        symptoms: ["Chest pain", "Cyanosis", "Cough", "Haemoptysis", "Difficulty breathing"],
    },
    {
        id: "circulatory-system",
        title: "Circulatory System",
        icon: "assets/icon_heart.png",
        tooltip:
            "The heart, blood vessels, and blood itself. Weak vessels lead to hemorrhages, poor blood circulation results in reduced vitality, and excessive blood flow causes heat in specific body parts.",
        symptoms: [
            "Severe pallor",
            "Hematomas",
            "Fever",
            "Burning sensation in the heart",
            "Rapid pulse",
            "Weakness",
            "Vein damage",
            "Slow pulse",
        ],
    },
    {
        id: "skin",
        title: "Skin",
        icon: "assets/icon_skin.png",
        tooltip:
            "The body's protective covering. It's important to distinguish between skin lesions and external manifestations of failures in other organ systems.",
        symptoms: [
            "Eczema",
            "Ichthyosis",
            "Stone disease",
            "Rash",
            "Skin redness",
            "Yellowing of the skin",
            "Itchy skin",
            "Insect bites",
            "Ulcers",
        ],
    },
    {
        id: "gastrointestinal-tract",
        title: "Gastrointestinal Tract",
        icon: "assets/icon_stomach.png",
        tooltip:
            "A system of organs involved in food consumption and digestion, as well as waste elimination. Disorders can lead to changes in body composition and eating behavior.",
        symptoms: [
            "Abdominal pain",
            "Diarrhea",
            "Dystrophy",
            "Geophagia",
            "Heartburn",
            "Belching",
            "Loss of appetite",
            "Nausea and vomiting",
        ],
    },
];

export const diagnoses = [
    {
        name: "Acute Bronchopathy",
        description: [
            "A subtype of diseases caused by Yersinia pestis. Transmitted by direct contact of the bacteria with mucous membranes, e.g., drinking from a dirty cup, smoking a pipe, or rinsing eyes with contaminated water.",
            "The acute phase starts with fever, muscle weakness, and a burning sensation in the heart area, followed by haemoptysis. The waning acute phase is marked by headaches and bursting pain in the chest. As the acute phase subsides, it becomes challenging to accurately diagnose. Without treatment, the patient dies within 2-3 days.",
        ],
        riskGroups: "People living in crowded conditions.",
        showcaseSymptoms: ["Haemoptysis", "Chest pain", "Headache"],
        symptoms: [
            "Headache",
            "Loss of coordination",
            "Chest pain",
            "Fever",
            "Difficulty breathing",
            "Cough",
            "Haemoptysis",
            "Redness around the nose",
            "Severe pallor",
            "Burning sensation in the heart",
            "Weakness",
        ],
    },
    {
        name: "Anemic Vasculopathy",
        description: [
            "An infectious disease caused by microorganisms from steppe soil entering the bloodstream. Cases of airborne transmission are also reported but require confirmation. The infection leads to anemia, which can manifest as patient pallor, muscle weakness, and weight loss. Occasionally, patients may experience localized bleeding and hematomas. Acute cases display burst capillaries on the eyes and high fever.",
        ],
        riskGroups:
            "Peasant plowmen, gravediggers, and other various types of people working with soil.",
        showcaseSymptoms: ["Dystrophy", "Cyanosis", "Red eyes"],
        symptoms: [
            "Hydrophobia",
            "Headache",
            "Red eyes",
            "Dystrophy",
            "Cyanosis",
            "Hematomas",
            "Severe pallor",
            "Fever",
        ],
    },
    {
        name: "Bonkowski's Fever",
        description: [
            "An extremely dangerous and contagious disease described in detail by Dr. Bonkowski. Epidemics of this disease can occur but are characteristic only for tropical inhabitants, i.e., those in hot and humid climates. Within the borders of the Empire, cases of this disease are extremely rare. Typically, the afflicted are pilgrims visiting southern countries for religious purposes or merchants involved in trade with tropical lands. The virus rapidly affects the lungs, leading to breathing difficulties. The heart muscle is then targeted, and at this stage, the disease is practically incurable.",
        ],
        riskGroups: "Pilgrims, traders, travelers visiting tropical countries.",
        showcaseSymptoms: ["Dystrophy"],
        symptoms: [
            "Bulimia",
            "Visual impairment",
            "Photophobia",
            "Fever",
            "Dystrophy",
            "Abdominal pain",
            "Belching",
            "Weakness",
            "Nausea and vomiting",
            "Burning sensation in the heart",
        ],
    },
    {
        name: "Burning Fever",
        description: [
            "A highly contagious disease caused by the neurolcera virus. Transmitted through contact and breathing.",
            "Initially, the disease presents with fever, headache, and abdominal pain. Later, ulcers and eczema appear on the skin. Itchy herpetic rashes are observed. The patient experiences psychosis. Frequent fatal outcomes among densely living and working population.",
        ],
        riskGroups: "People living in crowded conditions, people living in unsanitary conditions.",
        showcaseSymptoms: ["Ulcers", "Eczema", "Lip lesions"],
        symptoms: [
            "Hallucinations",
            "Headache",
            "Memory lapses",
            "Fever",
            "Loss of coordination",
            "Diarrhea",
            "Lip lesions",
            "Ulcers",
            "Eczema",
            "Rapid pulse",
        ],
    },
    {
        name: "Consumption",
        description: [
            "A chronic infectious disease. Mainly prevalent in countries with average to low living standards, where it takes on high mortality rates. The disease is caused by the bacterium Mycobacterium tuberculosis, for which humans are the main reservoir. It primarily affects the lungs and is transmitted through coughing, singing, and other respiratory actions. ",
            "Initially, patients complain of muscle weakness and weight loss. Cough and night fever are often among the initial symptoms. Skin dryness is present. In severe cases, haemoptysis occurs. High case fatality rate.",
        ],
        riskGroups: "Children, people with weakened immunity, smokers, drug addicts.",
        showcaseSymptoms: ["Dystrophy", "Ichthyosis"],
        symptoms: [
            "Loss of coordination",
            "Dystrophy",
            "Chest pain",
            "Fever",
            "Difficulty breathing",
            "Cough",
            "Haemoptysis",
            "Ichthyosis",
            "Weakness",
        ],
    },
    {
        name: "Fruit Typhoid",
        description: [
            "An infectious disease caused by bacteria found in sweet fruits and berries. The presumed natural reservoir is fruit-worm larvae.",
            "In the early stages, the primary symptoms are muscle weakness and chest pain, as the disease targets heart tissue. This is followed by gradual deterioration of vision and hearing. In later stages, a black rash appears, blood vessels darken—primarily on the hands and feet—and the shape of the pupil changes.",
        ],
        riskGroups: "Peasants, gardeners, fruit vendors, cooks, and berry pickers.",
        showcaseSymptoms: ["Rash", "Vein damage"],
        symptoms: [
            "Hallucinations",
            "Irregular pupil shape",
            "Chest pain",
            "Visual impairment",
            "Hearing impairment",
            "Rash",
            "Vein damage",
            "Weakness",
            "Slow pulse",
        ],
    },
    {
        name: "Hepatitis",
        description: [
            "Liver necrosis. Can be caused by viral infection. It can also develop in individuals who abuse alcohol or drugs.",
            "The preicteric phase of hepatitis is characterized by weight loss, nausea, and diarrhea. Sometimes skin itching and eczema occur. The icteric phase is marked by jaundice, with previous symptoms gradually regressing. The patient complains of pain in the liver area. Poor hygiene and substance abuse significantly increase the risk of death. Fatal in acute disease.",
        ],
        riskGroups: "Alcoholics, drug addicts, people with autoimmune disorders.",
        showcaseSymptoms: ["Yellowing of the skin", "Dystrophy", "Eczema"],
        symptoms: [
            "Visual impairment",
            "Dystrophy",
            "Stone disease",
            "Nausea and vomiting",
            "Itchy skin",
            "Eczema",
            "Yellowing of the skin",
            "Weakness",
        ],
    },
    {
        name: "Influenza",
        description: [
            "An acute respiratory disease caused by the influenza virus. Affects the respiratory tract. Considered the most severe among acute respiratory viral infections.",
            "The disease manifests suddenly with muscle weakness, fever, cough, sore throat, severe headache, and photophobia. Upper respiratory tract involvement starts with cough, chest pain, and runny nose. Later, throat pain, shortness of breath, and hoarseness appear. Rare strains of influenza can have gastrointestinal symptoms. Mortality from influenza increases in crowded conditions or during epidemics.",
        ],
        riskGroups: "Pregnant women, smokers, people living in crowded conditions.",
        showcaseSymptoms: ["Redness around the nose", "Cough", "Sore throat"],
        symptoms: [
            "Headache",
            "Nausea and vomiting",
            "Chest pain",
            "Sore throat",
            "Weakness",
            "Fever",
            "Photophobia",
            "Loss of appetite",
            "Difficulty breathing",
            "Cough",
            "Redness around the nose",
            "Hearing impairment",
            "Joint pain",
        ],
    },
    {
        name: "Ink Syndrome",
        description: [
            "Infection often found in sewage and stagnant water bodies. It can also be present in fish tissues. The virus alters the blood's chemical composition, resulting in the darkening of blood vessels in the eyes and throughout the body's circulatory system. Hallucinations and breathing difficulties in patients may indicate brain damage, and therefore an almost inevitable fatal outcome.",
        ],
        riskGroups:
            "People interacting with specific steppe water bodies of Gorkhon (washerwomen, shepherds, steppe dwellers).",
        showcaseSymptoms: ["Vein damage", "Darkened eye capillaries", "Cyanosis"],
        symptoms: [
            "Hallucinations",
            "Headache",
            "Memory lapses",
            "Irregular pupil shape",
            "Darkened eye capillaries",
            "Photophobia",
            "Difficulty breathing",
            "Chest pain",
            "Cyanosis",
            "Vein damage",
            "Hematomas",
        ],
    },
    {
        name: "Lymphotonitis",
        description: [
            "A natural focal disease caused by Yersinia pestis bacteria. Infection occurs through contact with infected patients, contaminated water, or mosquito bites carrying the bacteria.",
            "The infected experience muscle weakness, headache, and in some cases, dizziness. The bite area becomes itchy. Later, a rash with ulcer formation appears on the body. The patient experiences constant itching; ulcers may bleed. Compromised immunity and constant scratching of the ulcers can lead to complications and often death.",
        ],
        riskGroups: "People living in crowded conditions.",
        showcaseSymptoms: ["Insect bites", "Ulcers"],
        symptoms: [
            "Headache",
            "Loss of coordination",
            "Itchy skin",
            "Ulcers",
            "Insect bites",
            "Rapid pulse",
            "Skin redness",
            "Weakness",
        ],
    },
    {
        name: "Measles",
        description: [
            "A highly infectious viral disease with a very high transmission rate. It is marked by fever, inflammation of mucous tissues, conjunctivitis, and skin rash. The Metropolitan Infectionists Society suggests cattle as the virus source, but this theory doesn't have the unanimous support of the medical community. If the body overcomes the disease, then immunity develops, preventing future infections. However, fatal outcomes are possible, especially for malnourished patients without access to proper treatment and care.",
        ],
        riskGroups:
            "Children, as well as people spending a lot of time with children (teachers, mothers, mentors).",
        showcaseSymptoms: ["Skin redness", "Red eyes", "Sore throat"],
        symptoms: [
            "Headache",
            "Red eyes",
            "Photophobia",
            "Diarrhea",
            "Sore throat",
            "Skin redness",
            "Weakness",
            "Fever",
        ],
    },
    {
        name: "Nephropathia epidemica",
        description: [
            "A disease caused by a group of viruses, varying with the epidemic focus. Humans contract the virus from animals and their waste.",
            "The disease begins acutely with fever, rapid heartbeat, nausea, and/or vomiting. Accompanied by headache and photophobia. After 3 days, a rash appears on the skin and facial flushing becomes evident. The disease causes internal bleeding, leading to patient's death.",
        ],
        riskGroups: "People in contact with animals, rural residents.",
        showcaseSymptoms: ["Skin redness", "Rash"],
        symptoms: [
            "Hydrophobia",
            "Headache",
            "Bulimia",
            "Photophobia",
            "Visual impairment",
            "Heartburn",
            "Geophagia",
            "Rash",
            "Chest pain",
            "Nausea and vomiting",
            "Skin redness",
            "Rapid pulse",
            "Weakness",
            "Fever",
        ],
    },
    {
        name: "Pulmomucous Syndrome",
        description: [
            "An infectious disease caused by consuming water from contaminated steppe sources. The initial blow of the illness affects the human nervous system. In the next stage, it manifests through gastric disorders and ulcerative lesions on the lips. Subsequently, the patient loses appetite and experiences obsessive hallucinations. In advanced cases, breathing difficulties and deafness are observed, and at this stage, a fatal outcome is almost inevitable.",
        ],
        riskGroups:
            "People interacting with the waters of Gorkhon (washerwomen, water carriers, shepherds, steppe dwellers).",
        showcaseSymptoms: ["Redness around the nose", "Lip lesions"],
        symptoms: [
            "Loss of coordination",
            "Diarrhea",
            "Loss of appetite",
            "Difficulty breathing",
            "Redness around the nose",
            "Lip lesions",
            "Hallucinations",
            "Hearing impairment",
        ],
    },
    {
        name: "Serpent Syndrome",
        description: [
            "An infectious disease resulting from skin infections caused by the fungus hyacinthum petasum. The fungus is typical for eastern and southern provinces; cases of infection in the Empire's north are unknown. Presumably, the fungus affects impoverished people weakened by malnutrition. However, native steppe peoples seem to possess a certain immunity to this fungus. Northerners moving to steppe provinces lack such immunity and are more frequently affected. The disease starts with localized skin lesions that can later cover a significant portion of the patient's skin. Untreated cases lead to exhaustion, digestive system disorders, and damage to mucous membranes. All discharges from infected individuals are contagious, and patients require isolation and care with enhanced nutrition.",
        ],
        riskGroups: "Malnutritioned people, migrants to steppe provinces.",
        showcaseSymptoms: ["Ichthyosis", "Dystrophy", "Lip lesions"],
        symptoms: [
            "Loss of coordination",
            "Red eyes",
            "Diarrhea",
            "Visual impairment",
            "Dystrophy",
            "Lip lesions",
            "Difficulty breathing",
            "Ichthyosis",
        ],
    },
    {
        name: "Steppe Dryness",
        description: [
            "A natural focal fungal infection. Infection occurs through inhaling fungal spores present on steppe grass or as mold.",
            "The disease primarily develops in the lungs; patients complain of shortness of breath and rapid heartbeat. Irritation of mucous membranes is observed, manifested as throat pain and eye redness. In severe cases of intoxication, patients experience joint pain. Ichthyosis develops. The risk of fatality manifests if the case is advanced, when the patient can't move on their own.",
        ],
        riskGroups: "Inhabitants of the steppe.",
        showcaseSymptoms: ["Sore throat", "Red eyes", "Ichthyosis"],
        symptoms: [
            "Red eyes",
            "Photophobia",
            "Difficulty breathing",
            "Sore throat",
            "Joint pain",
            "Ichthyosis",
            "Rapid pulse",
        ],
    },
    {
        name: "Steppe Gastrodermal Fever",
        description: [
            "A viral disease caused by bites from the golden herb fly (Pluma herba aurea musca). A characteristic green rash appears around the bite area, and the disease progresses to affect the gastric mucosa, leading to vomiting and nausea. Some patients lose the ability to digest food normally and can only tolerate broths and liquid porridge. Symptoms also include extreme muscle weakness, exhaustion, and breathing difficulties. A fatal outcome is highly likely.",
        ],
        riskGroups:
            "People spending extensive period of time in the steppe, especially inhabitants of the steppe, shepherds, reapers, herbalists.",
        showcaseSymptoms: ["Rash", "Insect bites", "Dystrophy"],
        symptoms: [
            "Heartburn",
            "Geophagia",
            "Abdominal pain",
            "Rash",
            "Dystrophy",
            "Belching",
            "Nausea and vomiting",
            "Difficulty breathing",
            "Insect bites",
        ],
    },
    {
        name: "Stoneskin",
        description: [
            "A disease characterized by excessive skin cornification and densification. Infection occurs through skin contact with mycobacteria found in steppe flora.",
            "The disease starts with skin dryness, peeling, and itching. Subsequently, the skin thickens, resembling large petrified reptile scales. Itching on such skin disappears. Nonfatal.",
        ],
        riskGroups: "Travelers, inhabitants of the steppe.",
        showcaseSymptoms: ["Ichthyosis", "Red eyes"],
        symptoms: [
            "Red eyes",
            "Visual Impairment",
            "Photophobia",
            "Hearing Impairment",
            "Stone disease",
            "Itchy skin",
            "Slow pulse",
        ],
    },
    {
        name: "Tularemia",
        description: [
            "An infectious disease transmitted through food, contact with rodents, and insect bites.",
            "The onset is sudden, with fever, weakness, nausea, vomiting, diarrhea, and headache. Hallucinations are observed in some patients. Ulcers and/or redness then appear on the skin. It can also affect the eyes. Moderate mortality risk if left untreated. Immunity is permanent for recovered individuals. Not contagious from person to person.",
        ],
        riskGroups: "Impoverished people, inhabitants of the steppe.",
        showcaseSymptoms: ["Ulcers", "Red eyes", "Skin redness"],
        symptoms: [
            "Hallucinations",
            "Headache",
            "Nausea and vomiting",
            "Skin redness",
            "Ulcers",
            "Insect bites",
            "Weakness",
            "Fever",
        ],
    },
    {
        name: "Twyrine Syndrome",
        description: [
            'Infection by microorganisms found in twyre sprouts and products derived from twyre. Or a consequence of abusing twyre-based alcohol products ("twyrine").',
            'Patients experience muscle weakness, sweating, depressed mental state, migraines, and dizziness. Often accompanied by gastrointestinal symptoms. After 8-12 hours of exacerbation, hallucinations, photophobia, and seizures frequently manifest. Allergic reactions such as skin reddening/yellowing may occur. In more severe cases of intoxication, "twyrine" (epileptic) seizures occur. In extreme cases, it can lead to breathing difficulties, coma, and death.',
        ],
        riskGroups: "Alcoholics, inhabitants of the steppe.",
        showcaseSymptoms: ["Yellowing of the skin", "Red eyes", "Vein damage"],
        symptoms: [
            "Hallucinations",
            "Headache",
            "Memory lapses",
            "Loss of coordination",
            "Red eyes",
            "Photophobia",
            "Darkened eye capillaries",
            "Nausea and vomiting",
            "Yellowing of the skin",
            "Skin redness",
            "Vein damage",
            "Hematomas",
            "Weakness",
        ],
    },
    {
        name: "Cholera",
        description: [
            "An acute intestinal infection caused by contaminated water or food. Outbreaks flourish where wells, rivers, and storage vessels are fouled by human waste.",
            "The disease begins suddenly with violent diarrhea and repeated vomiting. The patient rapidly loses strength and bodily fluids; the pulse quickens, the face sharpens, and the extremities may turn blue from collapse. Without rehydration, death can follow within hours.",
        ],
        riskGroups:
            "People drinking unsafe water, riverbank dwellers, refugees, prisoners, and inhabitants of overcrowded rural settlements.",
        showcaseSymptoms: ["Cyanosis", "Headache"],
        symptoms: [
            "Headache",
            "Cyanosis",
            "Rapid pulse",
            "Weakness",
            "Severe pallor",
            "Diarrhea",
            "Loss of appetite",
            "Nausea and vomiting",
        ],
        custom: true,
    },
    {
        name: "Typhus",
        description: [
            "A severe infectious disease spread by body lice. It appears where people are crowded together, seldom washed, and forced to share bedding and clothing.",
            "The illness starts with fever, profound weakness, and splitting headache. Soon the patient develops red, inflamed eyes, becomes unsteady and confused, and a rash spreads across the skin. In grave cases delirium and collapse follow.",
        ],
        riskGroups:
            "People living in crowded, impoverished, or war-disrupted conditions; vagrants, prisoners, laborers, and refugees.",
        showcaseSymptoms: ["Rash", "Skin redness", "Red eyes"],
        symptoms: [
            "Headache",
            "Hallucinations",
            "Memory lapses",
            "Loss of coordination",
            "Red eyes",
            "Photophobia",
            "Rash",
            "Skin redness",
            "Weakness",
            "Fever",
        ],
        custom: true,
    },
    {
        name: "Favus",
        description: [
            "A chronic fungal disease of the skin, most often affecting the scalp. It spreads through prolonged close contact, shared bedding, hats, combs, and poor hygiene.",
            "At first the patient complains of itching and irritated skin. With time, crusted lesions and dry scaling develop, the skin becomes inflamed, and neglected cases lead to wasting and weakness. The disease lingers for months or years if untreated.",
        ],
        riskGroups:
            "Children in crowded households, impoverished rural families, and people sharing bedding or clothing.",
        showcaseSymptoms: ["Ichthyosis", "Skin redness"],
        symptoms: ["Itchy skin", "Ichthyosis", "Eczema", "Skin redness", "Dystrophy", "Weakness"],
        custom: true,
    },
    {
        name: "Pellagra",
        description: [
            "A wasting disease caused by prolonged poor diet, especially one dependent on badly prepared maize and lacking meat, milk, or legumes. It is not contagious, but flourishes where poverty dictates the table.",
            "The patient first grows weak and thin, then develops diarrhea and a red, rough rash on exposed skin. In advanced stages the mind is affected: memory falters, coordination worsens, and some patients become delirious or hallucinate.",
        ],
        riskGroups:
            "Poor peasants, widowed or neglected villagers, alcoholics, and people surviving on monotonous grain diets.",
        showcaseSymptoms: ["Skin redness", "Rash", "Dystrophy"],
        symptoms: [
            "Memory lapses",
            "Hallucinations",
            "Loss of coordination",
            "Weakness",
            "Skin redness",
            "Rash",
            "Dystrophy",
            "Diarrhea",
        ],
        custom: true,
    },
    {
        name: "Ergotism",
        description: [
            "A poisoning caused by eating rye or other grain infested with ergot fungus. It appears after bad harvest years, damp storage, or prolonged reliance on spoiled bread.",
            "Some patients suffer the convulsive form, with headache, vomiting, loss of coordination, and terrifying visions. Others develop a gangrenous form: the blood supply to the limbs fails, the flesh darkens, pain becomes unbearable, and ulcers may appear. Severe cases end in madness, maiming, or death.",
        ],
        riskGroups:
            "Peasants and laborers dependent on stored rye, especially in poor harvest years.",
        showcaseSymptoms: ["Vein damage", "Cyanosis", "Ulcers"],
        symptoms: [
            "Headache",
            "Hallucinations",
            "Memory lapses",
            "Loss of coordination",
            "Nausea and vomiting",
            "Weakness",
            "Cyanosis",
            "Vein damage",
            "Ulcers",
        ],
        custom: true,
    },
].sort((left, right) => {
    return left.name.localeCompare(right.name);
});

export const symptomImageVariants = {
    "Chest pain": ["sympt_chest_pain-1.png"],
    Cough: ["sympt_cough-1.png"],
    Cyanosis: ["sympt_cyanosis-1.png", "sympt_cyanosis-2.png"],
    Dystrophy: ["sympt_dystrophy-1.png", "sympt_dystrophy-2.png"],
    Eczema: ["sympt_eczema-1.png"],
    "Darkened eye capillaries": ["sympt_eye_capillaries-1.png"],
    Haemoptysis: ["sympt_haemoptysis-1.png"],
    Headache: ["sympt_headache-1.png"],
    Hematomas: ["sympt_hematomas-1.png"],
    Ichthyosis: ["sympt_ichtyosis-1.png", "sympt_ichtyosis-2.png"],
    "Insect bites": ["sympt_insect_bites-1.png"],
    "Lip lesions": ["sympt_lip_lesions-1.png", "sympt_lip_lesions_2.png"],
    "Loss of coordination": ["sympt_loss_coordination-1.png"],
    "Redness around the nose": ["sympt_nose_redness-1.png"],
    "Irregular pupil shape": ["sympt_pupil_shape-1.png"],
    Rash: ["sympt_rash-1.png", "sympt_rash-2.png", "sympt_rash-3.png"],
    "Red eyes": ["sympt_red_eyes-1.png"],
    "Skin redness": ["sympt_skin_redness-1.png", "sympt_skin_redness-2.png"],
    "Yellowing of the skin": ["sympt_skin_yellowing-1.png", "sympt_skin_yellowing-2.png"],
    "Sore throat": ["sympt_sore_throat-1.png"],
    "Stone disease": ["sympt_stone_disease-1.png"],
    Ulcers: ["sympt_ulcers-1.png"],
    "Vein damage": [
        "sympt_vein_damage-1.png",
        "sympt_vein_damage-2.png",
        "sympt_vein_damage-3.png",
    ],
};
